source "https://rubygems.org"

#rvm stuff
#ruby=ruby-2.5.0
#ruby-gemset=shrine


gem "roda", "~> 3.0"
gem "puma"

gem "tilt"

gem "sequel"
gem "sqlite3"

gem "shrine", "~> 2.0"
gem "tus-server", ">= 2.0.2", "< 3"
gem "shrine-tus", "~> 1.1"
gem "goliath-rack_proxy", "~> 1.0"
gem "foreman"
gem "google-api-client", "~> 0.13.0"
gem "dotenv"
